### ISSUE TITLE
ntlm_auth != ibgssapi + gss-ntlmssp + winbind?

### ISSUE THREAD

**Issue by 2f6465762f6e756c6c** [simo5/gss-ntlmssp#1]
So we have ubuntu clients that use sssd to authenticate with the AD.
Also we have websites that require ntlm_auth to do SSO.
As far as I am able to tell ntlm_auth is part of samba.
Am i correct in the assumption that i can't use winbind and the library libgssapi + gss-ntlmssp + firefox to do SSO with these websites?

**Comment by simo5** [comment]
Last I tested libgssapi + gss-ntlmssp + firefox + winbind worked fine.
SSSD can't do domain member NTLM auth though.
