### ISSUE TITLE
Add support for signing SMB2

### ISSUE THREAD

**Issue by amandeepgautam** [simo5/gss-ntlmssp#2]
Hi,
   I am trying to add support for signing for SMB v2 packets. I am using the client here: https://github.com/sahlberg/libsmb2

I have tried to add support here: https://github.com/amandeepgautam/gss-ntlmssp/commit/453653d6f7fa103ebff6232850b94a1562dcfaeb, but this does not yet work and I cannot figure out why. Can you please look?

**Comment by simo5** [comment]
Hi Aman,
can you give me more details about what is not working ?

The changes you make are reasonable, although I need to check if what you do is correct when a key exchange key is not requested.

**Comment by amandeepgautam** [comment]
I get the following error:
`Session setup failed with (0xc0000022) STATUS_ACCESS_DENIED.  (-13)`

It is from here: https://github.com/sahlberg/libsmb2/blob/a884d37f05cb96ea24d83429b6e0ea6b76509d43/lib/libsmb2.c#L503

I am hoping that the calculations are probably not correct or I am missing something. But cannot figure out why.

**Comment by simo5** [comment]
Looking at your patch the change you make for encrypted_session_key is incorrect, when NTLMSSP_NEGOTIATE_KEY_EXCH is not set then there is no encrypted_random_session_key to be sent around.

Why did you change that, what problem are you trying to resolve with that change ?

**Comment by simo5** [comment]
Your patch attempts to send the session key in the clear to the server, it would introduce a total breach of security.

**Comment by simo5** [comment]
> I get the following error:
> `Session setup failed with (0xc0000022) STATUS_ACCESS_DENIED. (-13)`
> 
> It is from here: https://github.com/sahlberg/libsmb2/blob/a884d37f05cb96ea24d83429b6e0ea6b76509d43/lib/libsmb2.c#L503
> 
> I am hoping that the calculations are probably not correct or I am missing something. But cannot figure out why.

ACCESS_DENIED may be due to numerous reasons, I am not familiar with libsm2 but a tree connect usually happens after authentication and access denied at that point simply means your user has no access. Is there evidence that this is due to an issue in NTLMSSP ?

**Comment by amandeepgautam** [comment]
I am very unfamiliar with SMB etc. so my patch is mostly based on experimentation. Here is how I thought this needs to be done:

Details about the internal setup:

We have 2 versions of client:
a) one using ntlmssp plugin with libsmb2 ()
b) other using libsamba (https://github.com/samba-team/samba/)
and for experimentation we also built:
c) native ntlmssp support with libsmb2 (libsmb2 comes with a very minimal support for ntlmssp)

(a), (c) share the same code. (b) is a different implementation.

> Looking at your patch the change you make for encrypted_session_key is incorrect, when NTLMSSP_NEGOTIATE_KEY_EXCH is not set then there is no encrypted_random_session_key to be sent around.
> 
> Why did you change that, what problem are you trying to resolve with that change ?

In packet traces captured for (b), I saw session key being sent. So, thought that maybe that is why I am getting ACCESS_DENIED. Hence the change. I can revert that bit.

> Your patch attempts to send the session key in the clear to the server, it would introduce a total breach of security.

Apologies. I am very new to this.

> ACCESS_DENIED may be due to numerous reasons, I am not familiar with libsm2 but a tree connect usually happens after authentication and access denied at that point simply means your user has no access. Is there evidence that this is due to an issue in NTLMSSP ?

Using (b), (c) I can access the file. So, I concluded the changes I have made do not work.

**Comment by simo5** [comment]
> Using (b), (c) I can access the file. So, I concluded the changes I have made do not work.

If you can provide me pcap traces of a working and a non-working case I
can help you establish if a NTLMSSP issue is likely or if there is a
configuration difference you need to clear first.

Simo.

-- 
Simo Sorce
RHEL Crypto Team
Red Hat, Inc

**Comment by amandeepgautam** [comment]
Sure. Let me get those to you. Will update in few mins.

**Comment by amandeepgautam** [comment]
Please find the attached network traces

**Comment by amandeepgautam** [comment]
Please find the attached traces for 3 traces. the names are corresponding to the options (a), (b) and (c).

[traces.zip](https://github.com/simo5/gss-ntlmssp/files/3942133/traces.zip)

**Comment by amandeepgautam** [comment]
@simo5 I looked into this more. Comparing with (c), I identified that there is a difference in how ntlmv2 response is calculated and made the following change: https://github.com/amandeepgautam/gss-ntlmssp/commit/368a1e0cfaf4e695950f8e3f9fceb517879c0c5f#diff-8f904654e790490f29504524e46f5b71L125.

We should pass target_info instead of client_target_info as suggested in this document as well: http://davenport.sourceforge.net/ntlm.html#theNtlmv2Response

It is still not working after this change, so let me know if you agree with it.

**Comment by simo5** [comment]
Aman, completely ignore davenport's stuff, it is often wrong.
Microsoft published the full protocol in MS-NLMP, that's your reference, if you read ntlmssp source code you will see many references to sections of the document.

Replying back the server target_info is wrong in general, because the target_info must contain only what the client understands it supports.

If there are missing/additional fields we need to figure out why. Blindly copying over target_info is not going to help you as you will claim things to the servert that the client code is then not aware of. The client and server behavior expectations will go out of sync then.

**Comment by simo5** [comment]
@amandeepgautam in the failing one (A) you are not negotiating the same NTLMSSP flags as the successful one.
Can you show me the code around where you call the GSSAPI interface in the non-working example and the working one ?

**Comment by amandeepgautam** [comment]
> Aman, completely ignore davenport's stuff, it is often wrong.
> Microsoft published the full protocol in MS-NLMP, that's your reference, if you read ntlmssp source code you will see many references to sections of the document.
> 
> Replying back the server target_info is wrong in general, because the target_info must contain only what the client understands it supports.
> 
> If there are missing/additional fields we need to figure out why. Blindly copying over target_info is not going to help you as you will claim things to the servert that the client code is then not aware of. The client and server behavior expectations will go out of sync then.

Sure.

> @amandeepgautam in the failing one (A) you are not negotiating the same NTLMSSP flags as the successful one.
> Can you show me the code around where you call the GSSAPI interface in the non-working example and the working one ?

@simo5 In the non-working case we set the flags here(in the plugin): https://github.com/simo5/gss-ntlmssp/blob/75e3840fc7d7471235a8e1edaf114b0ba735e377/src/gss_sec_ctx.c#L127 (and following lines) and we get the response from the server and then do the negotiation.

In the working case (Option C), libsmb2 generates the packet and flags related part is here:
https://github.com/sahlberg/libsmb2/blob/a884d37f05cb96ea24d83429b6e0ea6b76509d43/lib/ntlmssp.c#L164

Why do you think that flag negotiation can lead to a difference?

**Comment by simo5** [comment]
Sol one key difference is that NTLMSSP_NEGOTIATE_KEY_EXCH is set only if you pass the GSS_C_CONF_FLAG to the api when you gss_init_sec_context(), are you requesting any flags when making that call ?

Admittedly we may want to set that flag also when just requesting integrity (GSS_C_INTEG_FLAG only), it would make sense, so I would accept a patch in hat sense if required.

Another difference I noiticed is that gssntlmssp never sets the NTLMSSP_NEGOTIATE_VERSION, I forgot why, possibly an omission error, but I do not think it should make a difference for your case.

We should definitely concentrate on getting the key exchange flag set first, given that has security relevance and it is possible your server requires it and doesn't like it when the client does not set it.

**Comment by simo5** [comment]
I just realized you are using the lower level API in libssh ... ok, in that case please just add NTLMSSP_NEGOTIATE_KEY_EXCH to the neg_flags and you'll also need NTLMSSP_NEGOTIATE_SIGN for sure if you want to do signing.

**Comment by amandeepgautam** [comment]
@simo5 hmm...will try that. A quick question though: why does Option C, which also seems to be doing signing not require those flags?

**Comment by amandeepgautam** [comment]
@simo5 tried with the NTLMSSP_NEGOTIATE_KEY_EXCH flag and things work now. So, what is the take away here: if NTLMSSP_NEGOTIATE_SIGN is there, enforce NTLMSSP_NEGOTIATE_KEY_EXCH flag so that things work?

Also, do you not think that it is worth investigating why NTLMSSP_NEGOTIATE_SIGN does not work without NTLMSSP_NEGOTIATE_KEY_EXCH? It should right?

**Comment by amandeepgautam** [comment]
@simo5 updated the change here: https://github.com/amandeepgautam/gss-ntlmssp/commit/1a73db97a9c6c1e9d935760040bbcce660c81058
Let me know if I should send out a pull request.

**Comment by simo5** [comment]
On Tue, 2019-12-10 at 16:54 -0800, Aman Deep Gautam wrote:
> @simo5 hmm...will try that. A quick question though: why does Option C, which also seems to be doing signing not require those flags?

In the traces you sent I see those flags.

-- 
Simo Sorce
RHEL Crypto Team
Red Hat, Inc

**Comment by simo5** [comment]
On Tue, 2019-12-10 at 17:08 -0800, Aman Deep Gautam wrote:
> @simo5 tried with the NTLMSSP_NEGOTIATE_KEY_EXCH flag and things work
> now. So, what is the take away here: if NTLMSSP_NEGOTIATE_SIGN is
> there, enforce NTLMSSP_NEGOTIATE_KEY_EXCH flag so that things work?
> 
> Also, do you not think that it is worth investigating why
> NTLMSSP_NEGOTIATE_SIGN does not work without
> NTLMSSP_NEGOTIATE_KEY_EXCH? It should right?

Yes investigation would be nice, not clear if it should, there may be
other flags that influence that as well as server side minimum security
settings.

Simo.

**Comment by simo5** [comment]
On Tue, 2019-12-10 at 17:40 -0800, Aman Deep Gautam wrote:
> @simo5 updated the change here: https://github.com/amandeepgautam/gss-ntlmssp/commit/1a73db97a9c6c1e9d935760040bbcce660c81058
> 
> Let me know if I should send out a pull request.

A pull request to extract the SSPI session key is fine, but I can't add KEY_EXCH as a default flag as that will make the library incompatible with some of the uses.
Key Exchange is required only when SIgning and/or Sealing are requested.

If you are using the gssapi interface that means setting ths GSS_C_CONF_FLAG flag, if you are using the lowe rinterface directly you just need to use set the flag on your own for now.

Simo.

**Comment by amandeepgautam** [comment]
> On Tue, 2019-12-10 at 17:40 -0800, Aman Deep Gautam wrote: @simo5 updated the change here: [amandeepgautam@1a73db9](https://github.com/amandeepgautam/gss-ntlmssp/commit/1a73db97a9c6c1e9d935760040bbcce660c81058) Let me know if I should send out a pull request.
> A pull request to extract the SSPI session key is fine, but I can't add KEY_EXCH as a default flag as that will make the library incompatible with some of the uses. Key Exchange is required only when SIgning and/or Sealing are requested. If you are using the gssapi interface that means setting ths GSS_C_CONF_FLAG flag, if you are using the lowe rinterface directly you just need to use set the flag on your own for now. Simo.

How about if we set the flag only with NTLMSSP_NEGOTIATE_SIGN:
https://github.com/simo5/gss-ntlmssp/blob/75e3840fc7d7471235a8e1edaf114b0ba735e377/src/gss_sec_ctx.c#L143?

So, if someone requests GSS_C_REPLAY_FLAG flag, that would mean we set NTLMSSP_NEGOTIATE_SIGN and NTLMSSP_NEGOTIATE_KEY_EXCH. Is that an acceptable change? 

In our case, we use gss_init_context api and request the following flags: https://github.com/sahlberg/libsmb2/blob/2a58027e8464667a0b0215c3bac71b28dca7bf50/lib/krb5-wrapper.c#L358

**Comment by amandeepgautam** [comment]
> On Tue, 2019-12-10 at 16:54 -0800, Aman Deep Gautam wrote: @simo5 hmm...will try that. A quick question though: why does Option C, which also seems to be doing signing not require those flags?
> In the traces you sent I see those flags.
> […](#)
> -- Simo Sorce RHEL Crypto Team Red Hat, Inc

A little digression, getting back to an old comment: In option (c), we do not even negotiating NTLMSSP_NEGOTIATE_SIGN (or NTLMSSP_NEGOTIATE_KEY_EXCH). How is it working there?

**Comment by simo5** [comment]
> > On Tue, 2019-12-10 at 17:40 -0800, Aman Deep Gautam wrote: @simo5 updated the change here: [amandeepgautam@1a73db9](https://github.com/amandeepgautam/gss-ntlmssp/commit/1a73db97a9c6c1e9d935760040bbcce660c81058) Let me know if I should send out a pull request.
> > A pull request to extract the SSPI session key is fine, but I can't add KEY_EXCH as a default flag as that will make the library incompatible with some of the uses. Key Exchange is required only when SIgning and/or Sealing are requested. If you are using the gssapi interface that means setting ths GSS_C_CONF_FLAG flag, if you are using the lowe rinterface directly you just need to use set the flag on your own for now. Simo.
> 
> How about if we set the flag only with NTLMSSP_NEGOTIATE_SIGN:

You can have signing without key exchange (when using NTLMv1 for example).

> https://github.com/simo5/gss-ntlmssp/blob/75e3840fc7d7471235a8e1edaf114b0ba735e377/src/gss_sec_ctx.c#L143
> ?

I think I would agree adding by default the request to use KEY_EXCH in the GSS_C_INTEG_FLAG case, I think that's the main bug here.

> So, if someone requests GSS_C_REPLAY_FLAG flag, that would mean we set NTLMSSP_NEGOTIATE_SIGN and NTLMSSP_NEGOTIATE_KEY_EXCH. Is that an acceptable change?

GSS_C_REPLAY_FALG is in no way related to key exchange

> In our case, we use gss_init_context api and request the following flags: https://github.com/sahlberg/libsmb2/blob/2a58027e8464667a0b0215c3bac71b28dca7bf50/lib/krb5-wrapper.c#L358

In this case I think you should use GSS_C_INTEG_FLAG to indicate you want to do signing later.
Even though SMB Signing is done outside of the NTLMSSP provider.

HTH.

**Comment by simo5** [comment]
FYI: I pushed a few commits to master to add KEY_EXCH also when just GSS_C_INTEG_FLAG is requested.

Let me know if that is sufficient.

**Comment by amandeepgautam** [comment]
@simo5 yeah that is sufficient. I will get a pull request for extracting the keys.

**Comment by simo5** [comment]
Ok, in that case I'll close this issue as resolved.
