### ISSUE TITLE
Any chanche to Mac OSX Compatibility?

### ISSUE THREAD

**Issue by gianlucaciarcelluti** [simo5/gss-ntlmssp#7]
I would like to know if Mac OSX compatibility is in planning.

Thanks a lot.

**Comment by simo5** [comment]
I do not own Macs so I am not planning on adding any specific support myself (if anything is needed), but patches are welcome. The only problem is that I do not have a ay to test them either, so I would depend on community testing for them.
Are you aware of actual issues with the current code ?
Also not that currently this mechanism is only test with MIT krb5, if you are looking for compatibility with the native Mac OSX implementation that would mean first making sure this module works with Heimdal (which is what Mac OSX is loosely based on).
