### ISSUE TITLE
how to build it for alpine 3.1

### ISSUE THREAD

**Issue by krishnasingh1818** [simo5/gss-ntlmssp#8]
hi , is there any set of instruction we can follow to include it in alpine image

RUN apk add gss-ntlmssp   is not working 

pls advise

**Comment by krishnasingh1818** [comment]
It's a package installer for Alpine. Currently there is no package created
for ntlmssp library which can be in installed on Alpine using apk package
installer.

**Comment by simo5** [comment]
@krishnasingh1818 is there something in this code repo that breaks it?
I cannot help with packaging for random distributions, sorry.
